version: '3'
services:
    web:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - './target:/usr/local/tomcat/webapps'
        depends_on:
            - mydb
    mydb:
        image: mysql
        environment: 
                 MYSQL_ROOT_PASSWORD: test
                 MYSQL_DATABASE: test
                 MYSQL_USER: test
                 MYSQL_PASSWORD: test

